### ISSUE TITLE
Switch between photocamera and camcorder modes by swiping left and right

### ISSUE THREAD

**Issue by VGumbakis** [SimpleMobileTools/Simple-Camera#225]
Switch between photo and videorecorder modes by swiping left and right
Like in iphone cam app

**Comment by fritexvz** [comment]
Well, firstly, you have to use fragments. 
Second, you have to draw the camera surface and layout. 
After that, make it functional with Camera2, or even better use the newest Jetpack CameraX (https://developer.android.com/jetpack/androidx/releases/camera).

Moreover, your app should be compatible with Android OS 5.1 and newer, because you cannot read/write internal & external storage.
- https://github.com/syncthing/syncthing-android/issues/29

Android 4.0, 4.1, 4.2, 4.3 and even 5.0 are affected by the issue of Google, not having an option to change the permission for your application.

You cannot even call the request for permission, because it does not exist as is in the stated Android OS versions.

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
